"""Render generated Legacy data as the addon's Data/Legacy.lua (stdlib only)."""

COMPLETION_CATEGORIES = ("areas", "taxis", "dungeons", "raids", "legacy", "reputations")


def lua_string(value):
    return (
        '"'
        + "".join(
            "\\" + char if char in ('"', "\\") else f"\\{ord(char):03d}" if ord(char) < 32 else char for char in value
        )
        + '"'
    )


def named_refs(entry):
    refs = ", ".join(f"{{ {a}, {c} }}" for a, c in entry["refs"])
    return [f"name = {lua_string(entry['name'])}", f"refs = {{ {refs} }}"]


def render_entry(fields, depth, refs=()):
    indent = "\t" * depth
    compact = "{ " + ", ".join(fields) + " },"
    if len(compact) + depth * 4 <= 120:
        return [indent + compact]
    lines = [indent + "{"]
    for field in fields:
        if field.startswith("refs =") and len(field) + (depth + 1) * 4 + 1 > 120:
            lines.append(indent + "\trefs = {")
            lines.extend(indent + f"\t\t{{ {a}, {c} }}," for a, c in refs)
            lines.append(indent + "\t},")
        else:
            lines.append(indent + "\t" + field + ",")
    lines.append(indent + "},")
    return lines


def render(build, source_date, rewards, feeds, zones, completion):
    lines = [
        f"-- Generated by tools/gen_legacy.py from WoW: Forever build {build}. Do not edit by hand.",
        f"-- Source snapshot: {source_date}; https://wago.tools/db2/ (pinned CSV exports).",
        "---@type string, LegacyForeverNamespace",
        "local _, ns = ...",
        "",
        "ns.Data = {",
        f'\tbuild = "{build}",',
        "\t-- Reward-bearing Legacy challenges (both variant sets).",
        "\trewards = {",
    ]
    lines.extend(f"\t\t[{key}] = true," for key in sorted(rewards))
    lines.extend(["\t},", "\t-- Supporting achievement -> reward-bearing challenges it counts toward.", "\tfeeds = {"])
    for key, targets in sorted(feeds.items()):
        lines.append(f"\t\t[{key}] = {{ {', '.join(map(str, sorted(targets)))} }},")
    lines.extend(["\t},", "\t-- Location-bound objectives by zone uiMapID.", "\tzones = {"])
    for zone, entries in sorted(zones.items()):
        lines.append(f"\t\t[{zone}] = {{")
        for entry in sorted(entries, key=lambda e: (e["kind"], e["achievement"], e["criteria"])):
            fields = [
                f"achievement = {entry['achievement']}",
                f"criteria = {entry['criteria']}",
                f'kind = "{entry["kind"]}"',
            ]
            if "instance" in entry:
                fields.append(f"instance = {entry['instance']}")
            if "key" in entry:
                fields.append(f"key = {lua_string(entry['key'])}")
            if "x" in entry:
                fields.extend((f"x = {entry['x']:.3f}", f"y = {entry['y']:.3f}"))
            lines.extend(render_entry(fields, 3))
        lines.append("\t\t},")
    lines.extend(
        [
            "\t},",
            "\t-- Zone completion: areas, taxis, dungeon wings, raids, Legacy objectives, and reputations.",
            "\tcompletion = {",
        ]
    )
    for zone, categories in sorted(completion.items()):
        lines.append(f"\t\t[{zone}] = {{")
        lines.extend(f"\t\t\t{key} = {categories[key]}," for key in ("tileWidth", "tileHeight"))
        for category in COMPLETION_CATEGORIES:
            entries = categories[category]
            if not entries:
                lines.append(f"\t\t\t{category} = {{}},")
                continue
            lines.append(f"\t\t\t{category} = {{")
            order = {"areas": "key", "taxis": "node"}.get(category, "name")
            for entry in sorted(entries, key=lambda e: (e[order], e.get("refs", []), e.get("faction", 0))):
                if category == "raids":
                    lines.extend(
                        ["\t\t\t\t{", f"\t\t\t\t\tname = {lua_string(entry['name'])},", "\t\t\t\t\tbosses = {"]
                    )
                    for boss in entry["bosses"]:
                        lines.extend(render_entry(named_refs(boss), 6, boss["refs"]))
                    lines.extend(["\t\t\t\t\t},", "\t\t\t\t},"])
                    continue
                elif category == "areas":
                    fields = [f"key = {lua_string(entry['key'])}", f"name = {lua_string(entry['name'])}"]
                    if "hit" in entry:
                        fields.append("hit = { " + ", ".join(map(str, entry["hit"])) + " }")
                    if "tiles" in entry:
                        tiles = ", ".join(map(str, entry["tiles"]))
                        fields.append(f"tiles = {{ {tiles} }}")
                elif category == "taxis":
                    fields = [
                        f"node = {entry['node']}",
                        f"faction = {lua_string(entry['faction'])}",
                        f"name = {lua_string(entry['name'])}",
                    ]
                elif category == "reputations":
                    fields = [f"faction = {entry['faction']}", f"name = {lua_string(entry['name'])}"]
                    if "side" in entry:
                        fields.append(f"side = {lua_string(entry['side'])}")
                else:
                    fields = named_refs(entry)
                # Match the repository's StyLua width without a formatter dependency.
                lines.extend(render_entry(fields, 4, entry.get("refs", ())))
            lines.append("\t\t\t},")
        lines.append("\t\t},")
    lines.extend(["\t},", "}"])
    return "\n".join(lines) + "\n"
